import type { Metadata } from 'next'
import { Zilla_Slab } from 'next/font/google'
import './globals.css'

const zillaslab = Zilla_Slab({
  weight: ['300', '400', '500', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-zillaslab'
})
export const metadata: Metadata = {
  title: 'My Next.js Library',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-background ${zillaslab.className}`}>{children}</body>
    </html>
  )
}
